/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Jaki
 */
public class Ganador extends javax.swing.JFrame {

    /**
     * Creates new form Ganador
     */
    FRM_FondoPricipal principal;
    public Ganador(FRM_FondoPricipal principal) {
        initComponents();
        this.principal=principal;
        this.setVisible(false);
        principal.ganador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gano = new javax.swing.JLabel();
        ganador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        gano.setBackground(new java.awt.Color(0, 204, 204));
        gano.setFont(new java.awt.Font("DilleniaUPC", 1, 48)); // NOI18N
        gano.setForeground(new java.awt.Color(0, 0, 153));
        gano.setText("Gano!!!");
        getContentPane().add(gano);
        gano.setBounds(390, 30, 120, 29);

        ganador.setBackground(new java.awt.Color(0, 0, 102));
        ganador.setFont(new java.awt.Font("Dotum", 0, 48)); // NOI18N
        ganador.setForeground(new java.awt.Color(0, 204, 255));
        ganador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/inicio.png"))); // NOI18N
        getContentPane().add(ganador);
        ganador.setBounds(0, 0, 1027, 501);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ganador;
    private javax.swing.JLabel gano;
    // End of variables declaration//GEN-END:variables
}
