/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import modelo.Jugador;

/**
 *
 * @author Jaki
 */
public class Registro_FRM_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Registro_FRM_Principal
     */
    String nombre;
    int puntos;
    
    FRM_FondoPricipal principal;
    public Registro_FRM_Principal() 
    {
        initComponents();
       Jugador juego= new Jugador(nombre);
        
    }
    public String  getNombre()
    {
        
        return this.nombre =jText_Nombre.getText();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Nombre = new javax.swing.JTextField();
        jugar = new javax.swing.JButton();
        Inicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1094, 501));
        setMinimumSize(new java.awt.Dimension(1094, 501));
        getContentPane().setLayout(null);
        getContentPane().add(jText_Nombre);
        jText_Nombre.setBounds(290, 100, 140, 30);

        jugar.setBackground(new java.awt.Color(0, 255, 204));
        jugar.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jugar.setForeground(new java.awt.Color(0, 0, 153));
        jugar.setText("JUGAR");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar);
        jugar.setBounds(270, 180, 110, 33);

        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/inicio.png"))); // NOI18N
        getContentPane().add(Inicio);
        Inicio.setBounds(0, 0, 1027, 501);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        principal =new FRM_FondoPricipal(this) ;
        principal.setVisible(true);
        this.setVisible(false);
                
                
                
        
    }//GEN-LAST:event_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_FRM_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inicio;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JButton jugar;
    // End of variables declaration//GEN-END:variables
}
